topnav_title: LivePerson Developers
# this appears on the top navigation bar next to the home button

site_title: LivePerson Developers
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: LivePerson
# this appears in the footer

disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

google_analytics: UA-96175782-1


extlinks:
  attributes: {target: _blank}
# This tells the onclick module which attribute to add to links

plugins:
  - algoliasearch-jekyll
  - jekyll-redirect-from


algolia:
  application_id: "1ITT6KY19C"
  index_name: "dev_BASE"
#values for the Algolia plugin


github: [metadata]
#needed so that Github APIs don't throw a fit

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 smart_quotes: ["apos", "apos", "quot", "quot"]

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true

description: "LivePerson Developer is the main repository for documentation of LivePerson APIs and SDKs."
# the description is used in the feed.xml file


url: https://developers.liveperson.com
# needed for sitemap.xml file only


Copyright: "https://www.liveperson.com/policies/copyright"
Disclaimer: "https://www.liveperson.com/policies/disclaimer"
TermsofUse: "https://www.liveperson.com/policies/terms-of-use"
APITermsofUse: "https://www.liveperson.com/policies/apitou"
PrivacyPolicy: "https://www.liveperson.com/policies/privacy"
#footer links
