https://developers.liveperson.com:
  type: upstream
  upstream: jekyll_app:http

https://{default}/:
  # [...]
  redirects:
    paths:
      "/https://{default}/events": { "to": "https://{default}/events.html" }
